config/routes.rb
MonsterFleet::Application.routes.draw do

  resources :fleets do
    member do
      post :webcam
    end
  end
  resources :monsters do
    member do
      post :webcam
    end
  end

  root :to => 'monsters#app'

end

app/models/fleet.rb
class Fleet < ActiveRecord::Base

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  attr_accessible :color, :description, :name, :image

  has_many :monsters

  validates_uniqueness_of :name,:color

  validates_length_of :name, :in => (5..20)
  validates_length_of :description, :in => (10..30)
  validates_format_of :color, :with => /^[a-fA-F0-9]{6}$/

  before_destroy :check_no_monsters_left

  def image_urls
    {
      :thumb => image.url(:thumb), 
      :medium => image.url(:medium), 
      :original => image.url(:original)
    }
  end

  def as_json(options={})
      super(:only => [:color,:name,:description,:id],:methods => :image_urls)
  end

  private

  def check_no_monsters_left
    monsters.size == 0
  end

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  attr_accessible :description, :name, :image, :fleet_id

  validates_uniqueness_of :name

  validates_length_of :name, :in => (5..20)
  validates_length_of :description, :in => (10..30)
  validates_presence_of :fleet_id
  validates_presence_of :fleet, :message => "does longer not exist"

  belongs_to :fleet

  def image_urls
    {
      :thumb => image.url(:thumb), 
      :medium => image.url(:medium), 
      :original => image.url(:original)
    }
  end

  def as_json(options={})
      super(:only => [:fleet_id,:name,:description,:id],:methods => :image_urls)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fleets_controller.rb
class FleetsController < ApplicationController

  def webcam
    @fleet = Fleet.find(params[:id])

    fname = File.join(Rails.root,'public','uploads',"#{SecureRandom.hex}.jpg");
    File.open(fname, 'w') do |f|
      f.write request.raw_post.force_encoding("UTF-8")
    end
    @fleet.image = File.new(fname)
    @fleet.save
    File.unlink(fname)
    render :text => params[:id]
  end

  def index
    @fleets = Fleet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fleets }
    end
  end

  def show
    @fleet = Fleet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fleet }
    end
  end

  def new
    @fleet = Fleet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fleet }
    end
  end

  def edit
    @fleet = Fleet.find(params[:id])
  end

  def create
    @fleet = Fleet.new(params[:fleet])

    respond_to do |format|
      if @fleet.save
        format.html { redirect_to @fleet, notice: 'Fleet was successfully created.' }
        format.json { render json: @fleet, status: :created, location: @fleet }
      else
        format.html { render action: "new" }
        format.json { render json: @fleet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @fleet = Fleet.where(:id => params[:id]).first

    respond_to do |format|
      if ! @fleet
        format.html { redirect_to fleets_url, :notice=> 'Fleet does not exist.' }
        format.json { render :json => {:base => "Fleet does not exist! (someone might have deleted it)"} , :status => :unprocessable_entity }
      else
        if @fleet.update_attributes(params[:fleet])
          format.html { redirect_to @fleet, :notice=> 'Fleet was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render :json=> @fleet.errors, :status=> :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    @fleet = Fleet.find(params[:id])

    respond_to do |format|
      if @fleet.destroy
        format.html { redirect_to fleets_url }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: "Could not destory Fleet (check no monsters belong to this fleet)", status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

  def app
  end

  def webcam
    @monster = Monster.find(params[:id])

    fname = File.join(Rails.root,'public','uploads',"#{SecureRandom.hex}.jpg");
    File.open(fname, 'w') do |f|
      f.write request.raw_post.force_encoding("UTF-8")
    end
    @monster.image = File.new(fname)
    @monster.save
    File.unlink(fname)
    render :text => params[:id]
  end

  def index
    @monsters = Monster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @monsters }
    end
  end

  def show
    @monster = Monster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @monster }
    end
  end

  def new
    @monster = Monster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @monster }
    end
  end

  def edit
    @monster = Monster.find(params[:id])
  end

  def create
    @monster = Monster.new(params[:monster])

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render json: @monster, status: :created, location: @monster }
      else
        format.html { render action: "new" }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @monster = Monster.where(:id => params[:id]).first

    respond_to do |format|
      if ! @monster
        format.html { redirect_to monsters_url, :notice=> 'Monster does not exist.' }
        format.json { render :json => {:base => "Monster does not exist! (someone might have deleted it)"} , :status => :unprocessable_entity }
      else
        if @monster.update_attributes(params[:monster])
          format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @monster.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    if @monster = Monster.where(:id => params[:id]).first
      @monster.destroy
    end

    respond_to do |format|
      format.html { redirect_to monsters_url }
      format.json { head :no_content }
    end
  end

  private

  def upload_path(id) # is used in upload and create
    file_name = session[:session_id].to_s + '.jpg'
    File.join(Rails.root, 'public', 'uploads', file_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fleets_helper.rb
module FleetsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/fleets/_form.html.erb
<%= form_for(@fleet, :html => { :multipart => true } ) do |f| %>
  <% if @fleet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fleet.errors.count, "error") %> prohibited this fleet from being saved:</h2>
      <ul>
      <% @fleet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.text_area :description, :placeholder => "Description", :columns => 10, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.text_field :color, :placeholder => "Color (in hex)" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn-primary" %>
  </div>
<% end %>

app/views/fleets/edit.html.erb
<div class="span4">
  <h1>Editing fleet</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @fleet %> |
  <%= link_to 'Back', fleets_path %>
</div>

app/views/fleets/index.html.erb
<div class="span6">
  <h1>Listing fleets</h1>

  <table>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th>Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @fleets.each do |fleet| %>
      <tr>
        <td><%= fleet.name %></td>
        <td><%= image_tag fleet.image.url(:thumb) %></td>
        <td><%= fleet.description %></td>
        <td style="background-color:#<%=fleet.color%>"><%= fleet.color %></td>
        <td><%= link_to 'Show', fleet %></td>
        <td><%= link_to 'Edit', edit_fleet_path(fleet) %></td>
        <td><%= link_to 'Destroy', fleet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'New Fleet', new_fleet_path %>
</div>

app/views/fleets/new.html.erb
<h1>New fleet</h1>

<%= render 'form' %>

<%= link_to 'Back', fleets_path %>

app/views/fleets/show.html.erb
<div class="span6">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @fleet.name %>
  </p>

  <p>
    <b>Image :</b>
    <%= image_tag @fleet.image.url(:thumb) %>
  </p>

  <p>
    <b>Description:</b>
    <%= @fleet.description %>
  </p>

  <p style="background-color:#<%= @fleet.color %>">
    <b>Color:</b>
    <%= @fleet.color %>
  </p>


  <%= link_to 'Edit', edit_fleet_path(@fleet) %> |
  <%= link_to 'Back', fleets_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
     xmlns:og="http://ogp.me/ns#"
     xmlns:fb="http://www.facebook.com/2008/fbml">

<head>
  <title>MonsterFleet</title>

<meta charset="utf-8"/>

<%= csrf_meta_tag %>

<title>Manage your Monster Fleet (with Backbone !)</title>
<meta name="description" content="Monster Fleet Management"/>
<link rel="stylesheet" href="/stylesheets/bootstrap.css"/>
<link rel="stylesheet" href="/stylesheets/style.css"/>
<script src="/javascript/lib/jquery-1.7.1.js"></script>
</head>

<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">

        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Monster Fleet Management</a>
        <div class="nav-collapse">
          <p class="navbar-text pull-right">Management</p>
        </div>
      </div>
    </div>
  </div>

  <div class="top-row">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list">
          <li class="nav nav-list"><%= link_to "Unit Tests", "/jasmine.html" %></li>
          <li class="nav nav-list"><%= link_to "Root", "/#" %></li>
          <li class="nav nav-list"><%= link_to "Monsters JS", "/#monsters" %></li>
          <li class="nav nav-list"><%= link_to "Fleets JS", "/#fleets" %></li>
          <li class="nav nav-list"><%= link_to "Monsters HTML", "/monsters" %></li>
          <li class="nav nav-list"><%= link_to "Fleet HTML", "/fleets" %></li>
        </ul>
      </div>
    </div>

    <div>
      <%= yield %>
    </div>

  </div>

</body>

app/views/monsters/_form.html.erb
<%= form_for(@monster, :html => { :multipart => true } ) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Name" %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.text_area :description, :placeholder => "Description", :columns => 20, :rows => 10 %>
  </div>
  <div class="actions">
    <%= f.submit "Send", :class => "btn" %>
  </div>
<% end %>

app/views/monsters/app.html.erb
<script src="/javascript/lib/jquery.form.js"></script> 
<script src="/javascript/my_colors.js"></script>
<script src="/javascript/lib/webcam.js"></script>

<script type="text/javascript">
  $(document).ready(function(){

      window.csrf_param = $('meta[name=csrf-param]').attr('content');
      window.csrf_token = $('meta[name=csrf-token]').attr('content');

      window.router = new MonstersApp({pushState: true, el : "#multi_view" });
      Backbone.history.start();
      });

    webcam.set_swf_url('/webcam.swf');
    webcam.set_quality(90);
    webcam.set_shutter_sound(true, '/shutter.mp3');
</script>

<div id="multi_view">
</div>

<div class="span4">
  <ul>
    <li>A Fleet has many Monsters, so Monster belongs to a Fleet.</li>
    <li>You can edit Fleets and Monsters attributes in-line, click on 'edit' and then on the attribute you want to change.</li>
    <li>When you change any attribute on a Fleet, the views on monsters should be automatically updated as well.</li>
    <li>You can only destroy Fleets that have no monsters (validation is done on client and on server).</li>
    <li>Validations for attributes are done on client first: *if they pass on client* then validates on server side.</li>
    <li style="border:2px solid red;">Client-side validation errors are highlighted in red.</li>
    <li style="border:2px solid #00ff00;">Server-side errors are highlighted in green.</li>
    <li>
      <input type="checkbox" checked="true" onchange="window.router.toggle_client_validations()"></input>
      Perform Client Validations (vs. Server validations only)
    </li>
    <li>On each collection view change (ie. all -> monsters -> fleets) the full collections are fetched from server.</li>
  </ul>
</div>

<script type="text/template" id="notfound-template">
  <div class="span8">
    <h1>{= title =}</h1><a href="{= back_to =}">[back]</a>
    <div class="holding">
    </div>
  </div>
</script>

<script type="text/template" id="single-template">
  <div class="span8">
    <h1>{= title =}</h1><a href="{= back_to =}">[back]</a>
    <div class="holding">
    </div>
    <div class="fleets">
    </div>
  </div>
</script>

<script type="text/template" id="all-monsters-template">
  <div class="span8">
    <h1>Monsters</h1><a href="#">[back]</a>
    <div class="monsters">
    </div>
    <a href="#" class="new-monster btn-primary btn-large" >New Monster</a>
  </div>
</script>

<script type="text/template" id="all-fleets-template">
  <div class="span8">
    <h1>Fleets</h1><a href="#">[back]</a>
    <div class="fleets">
    </div>
    <a href="#" class="new-fleet btn-primary btn-large" >New Fleet</a>
  </div>
</script>

<script type="text/template" id="all-template">
  <div class="span4">
    <a href="#fleets"><h1>Fleets</h1></a>
    <div class="fleets">
    </div>
    <a href="#" class="new-fleet btn-primary btn-large" >New Fleet</a>
  </div>
  <div class="span4">
    <a href="#monsters"><h1>Monsters</h1></a>
    <div class="monsters">
    </div>
    <a href="#" class="new-monster btn-primary btn-large" >New Monster</a>
  </div>
</script>

<script type="text/template" id="monster-template">
  <div class="well monster {= is_editable_class() =} {= is_new_class() =}">
    <span class="destroy">[destroy]</span>
    <span class="make-editable">{= content_editable_text() =}</span>
    <div class="editable-holder name">
      <h3 data="name" {= content_editable_helper() =} class='name editable inline'><a href="#monsters/{= model.get('id') =}">{= model.get('name') =}</a></h3>
    </div>
    <div class="editable-holder description">
      <p data="description" {= content_editable_helper() =} class='description editable'>{= model.get('description') =}</p>
    </div>
    <div class="editable-holder image">
      <div class='imageEditable' data="{= model.get('id') =}">
        <img data="image_url" src='{= image_url() =}'></img>
      </div>
    </div>
    <div class="editable-holder fleet fleet_id">
      <div class="my_fleet">
      </div>
    </div>
  </div>
</script>

<script type="text/template" id="fleet-mini-template">
  {% if(typeof(model) == 'undefined'){ %} 
    <div class="one_fleet">
      <h4>Has no fleet</h4>
    </div>
  {% } else { %}
  <div class="one_fleet fleet" style="background-color:#{= model.get('color') =}">
    <h4>Belongs to fleet:</h4>
    <img style="width:30px;height:30px;" src='{= image_url() =}'></img>
    <bold class='inline'>{= model.get('name') =}</bold>
  </div>
  {% } %}
</script>

<script type="text/template" id="fleet-multi-template">
  <h4>Select the fleet to which this moster belongs</h4>
  {% _.each(model.collection.models, function(fleet){ if(fleet.isNew())return; %}
    <div data="{= fleet.get('id') =}" class="many_fleet fleet" style="background-color:#{= fleet.get('color') =}">
      <img style="width:30px;height:30px;" src='{= image_url(fleet) =}'></img>
      <bold class='inline'>{= fleet.get('name') =}</bold>
    </div>
    {% }); %}
</script>

<script type="text/template" id="fleet-template">
  <div class="well fleet {= is_editable_class() =} {= is_new_class() =}"
    style="background-color:#{= model.get('color') =}">
    <span class="destroy">[destroy]</span>
    <span class="make-editable">{= content_editable_text() =}</span>
    <div class="editable-holder name">
      <h3 data="name" {= content_editable_helper() =} class='name editable inline'><a href="#fleets/{= model.get('id') =}">{= model.get('name') =}</a></h3>
    </div>
    <div class="editable-holder description">
      <p data="description" {= content_editable_helper() =} class='description editable'>{= model.get('description') =}</p>
    </div>
    <div class="editable-holder color">
      <p>#<strong data="color" {= content_editable_helper() =} class='color editable'>{= model.get('color') || 'abc' =}</strong></p>
    </div>
    <div class="editable-holder image">
      <div class='imageEditable' data="{= model.get('id') =}">
        <img data="image_url" src='{= image_url() =}'></img>
      </div>
    </div>
  </div>
</script>

<script type="text/template" id="file-template">
  <div class="webcam_holder"></div>
  <input class="shoot" type="button" value="Take picture"/>
  <hr/>
  <form action='/{= resources =}/{= id =}' method="post" enctype="multipart/form-data">
    <input name="_method" type="hidden" value="put">
    <input name="{= resource =}[image]" type="file">
    <input name="commit" type="submit" value="Update {= resource =}" class="btn-primary">
  </form>
</script>

<script src="/javascript/lib/underscore-1.3.3.js"></script>
<script type="text/javascript">
  _.templateSettings = {
interpolate : /\{=([\s\S]+?)=\}/g,
               evaluate : /\{%([\s\S]+?)%\}/g
  };
</script>

<script src="/javascript/lib/backbone.js"></script>
<script src="/javascript/lib/bootstrap.js"></script>
<script src="/javascript/monster_fleet.js"></script>

app/views/monsters/edit.html.erb
<div class="span4">
  <h1>Editing monster</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @monster %> |
  <%= link_to 'Back', monsters_path %>
</div>

app/views/monsters/index.html.erb
<div class="span6">
  <h1>Listing monsters</h1>

  <table>
    <tr>
      <th>Image </th>
      <th>Name</th>
      <th>Description</th>
    </tr>

    <% @monsters.each do |monster| %>
      <tr>
        <td><%= image_tag monster.image.url(:thumb) %></td>
        <td><%= monster.name %></td>
        <td><%= monster.description %></td>
        <td><%= link_to 'Show', monster %></td>
        <td><%= link_to 'Edit', edit_monster_path(monster) %></td>
        <td><%= link_to 'Destroy', monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <br />

  <%= link_to 'New Monster', new_monster_path %>
</div>

app/views/monsters/new.html.erb
<h1>New monster</h1>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/photo.html.erb
<div id="webcam"></div>
<script src="/javascript/lib/webcam.js"></script> 

<script type="text/javascript">
    function onload_complete(msg) {
        // fetch the CSRF meta tag data
        var csrf_param = $('meta[name=csrf-param]').attr('content');
        var csrf_token = $('meta[name=csrf-token]').attr('content');

        // reset the api URL appending the auth token parameter
        webcam.set_api_url('<%= upload_monsters_path %>' + '?' + csrf_param + "=" + encodeURI(encodeURI(csrf_token)));
    }

    function upload_complete(msg) {
        if (msg == 'ok') {
            $('#new_photo').show();
            $('#photo_description').focus();
        } else {
            alert('An error occured');
            webcam.reset();
        }
    }

    webcam.set_swf_url('/webcam.swf');
    webcam.set_api_url('<%= upload_monsters_path %>');
    webcam.set_quality(90);
    webcam.set_shutter_sound(true, '/shutter.mp3');
    webcam.set_hook('onLoad', 'onload_complete');
    webcam.set_hook('onComplete', 'upload_complete');
    $('#webcam').html(webcam.get_html(300, 200));
</script>
<input type="button" value="Take picture" onclick="webcam.snap();"/>

<%= form_for Monster.new, :html => {:style => "display: none;"} do |f| %>
    <p>
      <%= f.text_field :name, :placeholder => "Name" %>
    </p>
    <p>
      <%= f.text_field :description, :placeholder => "Description" %>
    </p>
    <p>
      <%= f.submit "Save the photo" %>
      or <%= link_to "Take another", new_monster_path %>
    </p>
<% end %>

app/views/monsters/show.html.erb
<div class="span6">
  <p id="notice"><%= notice %></p>
  <p>
    <b>Name:</b>
    <%= @monster.name %>
  </p>
  <p>
    <b>Image :</b>
    <%= image_tag @monster.image.url(:medium) %>
  </p>
  <p>
    <b>Description:</b>
    <%= @monster.description %>
  </p>
  <p>
    <b>Fleet:</b>
    <%= link_to @monster.try(:fleet).try(:name), fleet_path(@monster.fleet)  %>
  </p>

  <%= link_to 'Edit', edit_monster_path(@monster) %> |
  <%= link_to 'Back', monsters_path %>
</div>